//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace itwebtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksTable
    {
        public int id { get; set; }
        public string Titre { get; set; }
        public string Auteur { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> DateP { get; set; }
        public string Editeur { get; set; }
        public Nullable<int> NBexmplr { get; set; }
    }
}
